=== danirz25/tecweb/practicas/p14/serviciovod_ep.dtd
<!ENTITY % regionValues "(MEX|USA|ESP|ARG|KOR)">

<!ELEMENT CatalogoVOD (cuenta, contenido)>
<!ELEMENT cuenta (perfil+)>
<!ELEMENT perfil EMPTY>
<!ATTLIST cuenta
    correo CDATA #REQUIRED>
<!ATTLIST perfil
    usuario CDATA #REQUIRED
    idioma CDATA #REQUIRED>
<!ELEMENT contenido (peliculas, series)>
<!ELEMENT peliculas (genero+)>
<!ATTLIST peliculas
    region %regionValues; "USA">
<!ELEMENT series (genero+)>
<!ATTLIST series
    region %regionValues; "USA">
<!ELEMENT genero (titulo+)>
<!ATTLIST genero
    nombre CDATA #REQUIRED>
<!ELEMENT titulo EMPTY>
<!ATTLIST titulo
    nombre CDATA #REQUIRED
    duracion CDATA #REQUIRED>

=== danirz25/tecweb/practicas/p14/serviciovod4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CatalogoVOD SYSTEM "serviciovod_ep.dtd">
<CatalogoVOD>
    <cuenta correo="danielpatino@alumno.buap.mx">
        <perfil usuario="Aimep3" idioma="español" />
        <perfil usuario="Kabezuko" idioma="inglés" />
    </cuenta>
    <contenido>
        <peliculas region="MEX">
            <genero nombre="Acción"
                <titulo nombre="Pollitos en fuga" duracion="120" />
                <titulo nombre="Chicken Little" duracion="90" />
            </genero>
        </peliculas>
        <series region="USA">
            <genero nombre="Comedia">
                <titulo nombre="¡Carly" duracion="45" />
                <titulo nombre="Drake y Josh" duracion="30" />
            </genero>
        </series>
    </contenido>
</CatalogoVOD>
